CREATE TABLE playlists (
  id bigint generated by default as identity,
  name text,
  created_at timestamp with time zone default now() not null,

  primary key (name)
);

CREATE TABLE videos (
  id bigint generated by default as identity,
  youtube_id text not null,
  title text,
  url text,
  thumb text,
  playlist text REFERENCES public.playlists on delete cascade not null,
  created_at timestamp with time zone default now() not null,

  primary key (id)
);

alter table public.videos
  replica identity full;
alter table public.playlists
  replica identity full;

begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table public.videos;
alter publication supabase_realtime add table public.playlists;